# Files


In [ ]:
!wget https://www.dropbox.com/s/w94odi4aqlk44lf/mobile_cleaned.csv

--2022-10-08 14:20:02--  https://www.dropbox.com/s/w94odi4aqlk44lf/mobile_cleaned.csv
Resolving www.dropbox.com (www.dropbox.com)... 162.125.5.18, 2620:100:601d:18::a27d:512
Connecting to www.dropbox.com (www.dropbox.com)|162.125.5.18|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘mobile_cleaned.csv’

mobile_cleaned.csv      [ <=>                ] 386.84K  2.02MB/s    in 0.2s    

2022-10-08 14:20:02 (2.02 MB/s) - ‘mobile_cleaned.csv’ saved [396120]



In [ ]:
import csv

In [ ]:
file = open('mobile_cleaned.csv', 'r')

In [ ]:
csvreader = csv.reader(file)

In [ ]:
for row in csvreader:
  print(row)
  break

['<!DOCTYPE html><html class="maestro global-header" lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml"><head><script nonce="voR0CL/YI8hsr8zq4T4g">']


In [ ]:
s = file.readline()

In [ ]:
print(s)

window.addEventListener('click', function(event) {



In [ ]:
!touch one.txt


In [ ]:
!echo "One Good Friend for Shankar which helps him against everything is knowledge" > one.txt

In [ ]:
!echo -e "One Good Friend for Shankar which helps him against everything is knowledge \nanother one is listening about mahavtar babaji" >one.txt

In [ ]:
!cat one.txt

One Good Friend for Shankar which helps him against everything is knowledge 
another one is listening about mahavtar babaji


In [ ]:
with open("one.txt", 'r') as file:
  for line in file:
    print(line)
    break

One Good Friend for Shankar which helps him against everything is knowledge 



In [ ]:
import numpy as np

In [ ]:
arr1 = np.arange(20).reshape(4,5)

In [ ]:
arr1.shape

(4, 5)

In [ ]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
import pandas as pd

In [ ]:
pd.Series(["shankar", 1, 2]).dtype

dtype('O')

In [ ]:
pd.Series([1,2]).dtype

dtype('int64')

In [ ]:
s = pd.Series([1,2,34,4])


In [ ]:
s.sum()

41

In [ ]:
s.product()

272

In [ ]:
s.mean()

10.25

In [ ]:
arr1 = ["one", 'Two', 'three', 'Four', 'Five']
arr2 = ["apple", "banana", "black Grape", "orange", "Kiwi"]


In [ ]:
pd.Series(data=arr2, index=arr1, name="Fruits List")

SyntaxError: ignored

In [ ]:
pd.Series(data=arr2, index=arr1)

one            apple
Two           banana
three    black Grape
Four          orange
Five            Kiwi
dtype: object

In [ ]:
pd.Series(arr2,arr1,object, "Fruits List")

one            apple
Two           banana
three    black Grape
Four          orange
Five            Kiwi
Name: Fruits List, dtype: object

In [27]:
df = pd.read_csv("pokemon.csv")

In [28]:
df.head()

Pokemon   Type
0   Bulbasaur  Grass
1     Ivysaur  Grass
2    Venusaur  Grass
3  Charmander   Fire
4  Charmeleon   Fire

In [29]:
df.cols

AttributeError: ignored

In [30]:
df.columns

Index(['Pokemon', 'Type'], dtype='object')

In [34]:
df1 = pd.read_csv("pokemon.csv", usecols=['Pokemon'],squeeze= True)

In [35]:
df1.head()

0     Bulbasaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
Name: Pokemon, dtype: object